import { NavStage, AIPipelineStage, PipelineStage } from '@/types'

// ─── Sidebar Navigation Stages (5 items) ──────────────────
export const NAV_STAGES: NavStage[] = [
  {
    id: 'document-upload',
    label: 'Document Upload',
    step: 1,
    icon: 'Upload',
    description: 'Upload job description document',
    route: '/',
  },
  {
    id: 'weightage-setting',
    label: 'Weightage Setting',
    step: 2,
    icon: 'Scale',
    description: 'Configure scoring criteria and weights',
    route: '/weightage',
  },
  {
    id: 'resume-upload',
    label: 'Resume Upload',
    step: 3,
    icon: 'FolderUp',
    description: 'Upload candidate resume files',
    route: '/resume-upload',
  },
  {
    id: 'candidate-ranking',
    label: 'Candidate Ranking',
    step: 4,
    icon: 'ListOrdered',
    description: 'Run AI pipeline and view ranked candidates',
    route: '/ranking',
  },
  {
    id: 'recruiter-dashboard',
    label: 'Recruiter Dashboard',
    step: 5,
    icon: 'LayoutDashboard',
    description: 'Review and action screened candidates',
    route: '/dashboard',
  },
]

// ─── AI Processing Pipeline (7 visual stages) ────────────────
export const AI_PIPELINE_STAGES: AIPipelineStage[] = [
  {
    id: 'document-ingestion',
    label: 'Document Ingestion',
    shortLabel: 'Ingestion',
    icon: 'FolderInput',
    description: 'Parse and ingest JD and resume files',
  },
  {
    id: 'weightage-setup',
    label: 'Weightage Setup',
    shortLabel: 'Weightage',
    icon: 'Scale',
    description: 'Apply configured scoring weights',
  },
  {
    id: 'ai-information-extraction',
    label: 'AI Information Extraction',
    shortLabel: 'Extraction',
    icon: 'ScanText',
    description: 'Extract candidate skills, experience, education',
  },
  {
    id: 'data-normalization',
    label: 'Data Normalization',
    shortLabel: 'Normalization',
    icon: 'GitMerge',
    description: 'Normalize and standardize extracted fields',
  },
  {
    id: 'matching-engine',
    label: 'Matching Engine',
    shortLabel: 'Matching',
    icon: 'Cpu',
    description: 'Semantic matching of candidates to JD',
  },
  {
    id: 'candidate-ranking',
    label: 'Candidate Ranking',
    shortLabel: 'Ranking',
    icon: 'ListOrdered',
    description: 'Rank candidates by weighted composite score',
  },
  {
    id: 'ai-explanation',
    label: 'AI Explanation',
    shortLabel: 'Explanation',
    icon: 'Sparkles',
    description: 'Generate AI rationale per candidate',
  },
]

// ─── Legacy PIPELINE_STAGES (used by store for step count) ────
export const PIPELINE_STAGES: PipelineStage[] = NAV_STAGES.map((s) => ({
  id: s.id,
  label: s.label,
  shortLabel: s.label,
  step: s.step,
  icon: s.icon,
  description: s.description,
}))

export const TOTAL_STEPS = NAV_STAGES.length

export const DEFAULT_WEIGHTS = [
  {
    id: 'skills' as const,
    label: 'Skills',
    description: 'Hard skills, tools, and technology matching',
    weight: 40,
    locked: false,
    color: '#f43f5e',
    badgeBg: '#ffe4e6',
    badgeText: '#be123c',
    iconBg: '#ffe4e6',
    iconColor: '#e11d48',
    icon: 'Code2',
  },
  {
    id: 'experience' as const,
    label: 'Experience',
    description: 'Years of service and role relevance',
    weight: 25,
    locked: false,
    color: '#10b981',
    badgeBg: '#dcfce7',
    badgeText: '#15803d',
    iconBg: '#dcfce7',
    iconColor: '#16a34a',
    icon: 'Briefcase',
  },
  {
    id: 'projects' as const,
    label: 'Projects',
    description: 'Relevant projects and achievements',
    weight: 15,
    locked: false,
    color: '#3b82f6',
    badgeBg: '#dbeafe',
    badgeText: '#1d4ed8',
    iconBg: '#dbeafe',
    iconColor: '#2563eb',
    icon: 'Folder',
  },
  {
    id: 'education' as const,
    label: 'Education',
    description: 'Degrees, institutions, and academic record',
    weight: 10,
    locked: false,
    color: '#f97316',
    badgeBg: '#ffedd5',
    badgeText: '#c2410c',
    iconBg: '#ffedd5',
    iconColor: '#ea580c',
    icon: 'GraduationCap',
  },
  {
    id: 'certifications' as const,
    label: 'Certifications',
    description: 'Professional licenses and verified credentials',
    weight: 5,
    locked: false,
    color: '#14b8a6',
    badgeBg: '#ccfbf1',
    badgeText: '#0f766e',
    iconBg: '#ccfbf1',
    iconColor: '#0d9488',
    icon: 'Award',
  },
  {
    id: 'languages' as const,
    label: 'Languages',
    description: 'Spoken and written language proficiency',
    weight: 5,
    locked: false,
    color: '#a855f7',
    badgeBg: '#f3e8ff',
    badgeText: '#7e22ce',
    iconBg: '#f3e8ff',
    iconColor: '#9333ea',
    icon: 'Globe',
  },
]

export const ROLE_PRESETS = [
  {
    id: 'balanced',
    label: 'Balanced',
    weights: {
      skills: 40,
      experience: 25,
      projects: 15,
      education: 10,
      certifications: 5,
      languages: 5,
    },
  },
  {
    id: 'tech-focus',
    label: 'Tech Focus',
    weights: {
      skills: 40,
      experience: 15,
      projects: 25,
      education: 5,
      certifications: 5,
      languages: 10,
    },
  },
  {
    id: 'entry-level',
    label: 'Entry Level',
    weights: {
      skills: 25,
      experience: 10,
      projects: 30,
      education: 25,
      certifications: 5,
      languages: 5,
    },
  },
  {
    id: 'executive',
    label: 'Executive',
    weights: {
      skills: 10,
      experience: 50,
      projects: 10,
      education: 15,
      certifications: 10,
      languages: 5,
    },
  },
]
