import { NavStage, AIPipelineStage, PipelineStage } from '@/types'

// ─── Sidebar Navigation Stages (5 items) ──────────────────
export const NAV_STAGES: NavStage[] = [
  {
    id: 'document-upload',
    label: 'Document Upload',
    step: 1,
    icon: 'Upload',
    description: 'Upload job description document',
    route: '/',
  },
  {
    id: 'weightage-setting',
    label: 'Weightage Setting',
    step: 2,
    icon: 'Scale',
    description: 'Configure scoring criteria and weights',
    route: '/weightage',
  },
  {
    id: 'resume-upload',
    label: 'Resume Upload',
    step: 3,
    icon: 'FolderUp',
    description: 'Upload candidate resume files',
    route: '/resume-upload',
  },
  {
    id: 'candidate-ranking',
    label: 'Candidate Ranking',
    step: 4,
    icon: 'ListOrdered',
    description: 'Run AI pipeline and view ranked candidates',
    route: '/ranking',
  },
  {
    id: 'recruiter-dashboard',
    label: 'Recruiter Dashboard',
    step: 5,
    icon: 'LayoutDashboard',
    description: 'Review and action screened candidates',
    route: '/dashboard',
  },
]

// ─── AI Processing Pipeline (7 visual stages) ────────────────
export const AI_PIPELINE_STAGES: AIPipelineStage[] = [
  {
    id: 'document-ingestion',
    label: 'Document Ingestion',
    shortLabel: 'Ingestion',
    icon: 'FolderInput',
    description: 'Parse and ingest JD and resume files',
  },
  {
    id: 'weightage-setup',
    label: 'Weightage Setup',
    shortLabel: 'Weightage',
    icon: 'Scale',
    description: 'Apply configured scoring weights',
  },
  {
    id: 'ai-information-extraction',
    label: 'AI Information Extraction',
    shortLabel: 'Extraction',
    icon: 'ScanText',
    description: 'Extract candidate skills, experience, education',
  },
  {
    id: 'data-normalization',
    label: 'Data Normalization',
    shortLabel: 'Normalization',
    icon: 'GitMerge',
    description: 'Normalize and standardize extracted fields',
  },
  {
    id: 'matching-engine',
    label: 'Matching Engine',
    shortLabel: 'Matching',
    icon: 'Cpu',
    description: 'Semantic matching of candidates to JD',
  },
  {
    id: 'candidate-ranking',
    label: 'Candidate Ranking',
    shortLabel: 'Ranking',
    icon: 'ListOrdered',
    description: 'Rank candidates by weighted composite score',
  },
  {
    id: 'ai-explanation',
    label: 'AI Explanation',
    shortLabel: 'Explanation',
    icon: 'Sparkles',
    description: 'Generate AI rationale per candidate',
  },
]

// ─── Legacy PIPELINE_STAGES (used by store for step count) ────
export const PIPELINE_STAGES: PipelineStage[] = NAV_STAGES.map((s) => ({
  id: s.id,
  label: s.label,
  shortLabel: s.label,
  step: s.step,
  icon: s.icon,
  description: s.description,
}))

export const TOTAL_STEPS = NAV_STAGES.length

export const DEFAULT_WEIGHTS = [
  {
    id: 'experience',
    label: 'Experience',
    description: 'Years of service and role relevance',
    weight: 40,
    locked: false,
    color: '#10b981',
    badgeBg: '#dcfce7',
    badgeText: '#15803d',
    iconBg: '#dcfce7',
    iconColor: '#16a34a',
    icon: 'Briefcase',
  },
  {
    id: 'domain-experience',
    label: 'Domain Experience',
    description: 'Industry/domain specific experience',
    weight: 25,
    locked: false,
    color: '#a855f7',
    badgeBg: '#f3e8ff',
    badgeText: '#7e22ce',
    iconBg: '#f3e8ff',
    iconColor: '#9333ea',
    icon: 'Globe',
  },
  {
    id: 'projects',
    label: 'Projects',
    description: 'Relevant projects and achievements',
    weight: 15,
    locked: false,
    color: '#3b82f6',
    badgeBg: '#dbeafe',
    badgeText: '#1d4ed8',
    iconBg: '#dbeafe',
    iconColor: '#2563eb',
    icon: 'Folder',
  },
  {
    id: 'education',
    label: 'Education',
    description: 'Degrees, institutions, and academic record',
    weight: 10,
    locked: false,
    color: '#f97316',
    badgeBg: '#ffedd5',
    badgeText: '#c2410c',
    iconBg: '#ffedd5',
    iconColor: '#ea580c',
    icon: 'GraduationCap',
  },
  {
    id: 'certifications',
    label: 'Certifications',
    description: 'Professional licenses and verified credentials',
    weight: 5,
    locked: false,
    color: '#14b8a6',
    badgeBg: '#ccfbf1',
    badgeText: '#0f766e',
    iconBg: '#ccfbf1',
    iconColor: '#0d9488',
    icon: 'Award',
  },
  {
    id: 'technical-skills',
    label: 'Technical Skills',
    description: 'Hard skills, tools, and technology matching',
    weight: 5,
    locked: false,
    color: '#f43f5e',
    badgeBg: '#ffe4e6',
    badgeText: '#be123c',
    iconBg: '#ffe4e6',
    iconColor: '#e11d48',
    icon: 'Code2',
  },
]

export const ROLE_PRESETS = [
  {
    id: 'balanced',
    label: 'Balanced',
    weights: {
      experience: 40,
      'domain-experience': 25,
      projects: 15,
      education: 10,
      certifications: 5,
      'technical-skills': 5,
    },
  },
  {
    id: 'tech-focus',
    label: 'Tech Focus',
    weights: {
      experience: 20,
      'domain-experience': 15,
      projects: 25,
      education: 5,
      certifications: 5,
      'technical-skills': 30,
    },
  },
  {
    id: 'entry-level',
    label: 'Entry Level',
    weights: {
      experience: 10,
      'domain-experience': 10,
      projects: 30,
      education: 25,
      certifications: 5,
      'technical-skills': 20,
    },
  },
  {
    id: 'executive',
    label: 'Executive',
    weights: {
      experience: 45,
      'domain-experience': 35,
      projects: 5,
      education: 10,
      certifications: 3,
      'technical-skills': 2,
    },
  },
]

export const MOCK_CANDIDATES = [
  {
    id: 'c1',
    name: 'Sarah Johnson',
    email: 'sarah.j@email.com',
    currentTitle: 'Senior Software Engineer',
    location: 'San Francisco, CA',
    resumeFile: 'sarah_johnson_resume.pdf',
    overallScore: 92,
    rank: 1,
    status: 'screened' as const,
    extractedFields: [],
    aiExplanation: 'Sarah demonstrates exceptional alignment with the role. Her 8 years of Python and cloud-native experience directly maps to the core JD requirements. Her AWS Solutions Architect certification and prior leadership of a team of 6 engineers signals strong technical and organizational fit. The only minor gap is limited exposure to Kubernetes in production, though her Docker expertise is extensive.',
    keyStrengths: ['8+ years Python & cloud experience', 'AWS certified architect', 'Team leadership background', 'FastAPI & microservices expertise'],
    keyWeaknesses: ['Limited Kubernetes production experience'],
    scores: [
      { criterionId: 'experience', label: 'Experience', score: 94, weight: 40, weightedScore: 37.6 },
      { criterionId: 'domain-experience', label: 'Domain Experience', score: 92, weight: 25, weightedScore: 23.0 },
      { criterionId: 'projects', label: 'Projects', score: 90, weight: 15, weightedScore: 13.5 },
      { criterionId: 'education', label: 'Education', score: 88, weight: 10, weightedScore: 8.8 },
      { criterionId: 'certifications', label: 'Certifications', score: 95, weight: 5, weightedScore: 4.75 },
      { criterionId: 'technical-skills', label: 'Technical Skills', score: 87, weight: 5, weightedScore: 4.35 },
    ],
  },
  {
    id: 'c2',
    name: 'Marcus Chen',
    email: 'marcus.c@email.com',
    currentTitle: 'Full Stack Developer',
    location: 'Austin, TX',
    resumeFile: 'marcus_chen_resume.pdf',
    overallScore: 87,
    rank: 2,
    status: 'screened' as const,
    extractedFields: [],
    aiExplanation: 'Marcus is a strong full-stack candidate with solid backend and frontend capabilities. His experience with React, Node.js, and PostgreSQL aligns well with the stack. He has contributed to open-source projects that demonstrate initiative. A 2-year gap in formal leadership roles and absence of cloud certifications slightly lower his overall score vs. the top candidate.',
    keyStrengths: ['React & Node.js expertise', 'Open-source contributor', 'PostgreSQL & Redis experience', 'Strong communication skills'],
    keyWeaknesses: ['No cloud certifications', 'Limited leadership experience'],
    scores: [
      { criterionId: 'experience', label: 'Experience', score: 85, weight: 40, weightedScore: 34.0 },
      { criterionId: 'domain-experience', label: 'Domain Experience', score: 88, weight: 25, weightedScore: 22.0 },
      { criterionId: 'projects', label: 'Projects', score: 92, weight: 15, weightedScore: 13.8 },
      { criterionId: 'education', label: 'Education', score: 82, weight: 10, weightedScore: 8.2 },
      { criterionId: 'certifications', label: 'Certifications', score: 78, weight: 5, weightedScore: 3.9 },
      { criterionId: 'technical-skills', label: 'Technical Skills', score: 90, weight: 5, weightedScore: 4.5 },
    ],
  },
  {
    id: 'c3',
    name: 'Priya Sharma',
    email: 'priya.s@email.com',
    currentTitle: 'ML Engineer',
    location: 'New York, NY',
    resumeFile: 'priya_sharma_resume.pdf',
    overallScore: 79,
    rank: 3,
    status: 'pending' as const,
    extractedFields: [],
    aiExplanation: 'Priya brings strong ML and data science expertise which partially overlaps with the role. Her published research in NLP and transformer models is a notable differentiator. However, the role requires more traditional software engineering skills — particularly RESTful API design, CI/CD pipelines, and service deployment — areas where Priya\'s profile is thinner. Recommend a technical interview to assess engineering depth.',
    keyStrengths: ['NLP & transformer research', 'Python & PyTorch mastery', 'Graduate education (M.Sc. ML)', 'Published researcher'],
    keyWeaknesses: ['Limited REST API & deployment experience', 'Short industry tenure (2 years)'],
    scores: [
      { criterionId: 'experience', label: 'Experience', score: 75, weight: 40, weightedScore: 30.0 },
      { criterionId: 'domain-experience', label: 'Domain Experience', score: 80, weight: 25, weightedScore: 20.0 },
      { criterionId: 'projects', label: 'Projects', score: 85, weight: 15, weightedScore: 12.75 },
      { criterionId: 'education', label: 'Education', score: 92, weight: 10, weightedScore: 9.2 },
      { criterionId: 'certifications', label: 'Certifications', score: 60, weight: 5, weightedScore: 3.0 },
      { criterionId: 'technical-skills', label: 'Technical Skills', score: 88, weight: 5, weightedScore: 4.4 },
    ],
  },
  {
    id: 'c4',
    name: 'Alex Rivera',
    email: 'alex.r@email.com',
    currentTitle: 'Backend Engineer',
    location: 'Seattle, WA',
    resumeFile: 'alex_rivera_resume.pdf',
    overallScore: 64,
    rank: 4,
    status: 'rejected' as const,
    extractedFields: [],
    aiExplanation: 'Alex has foundational backend skills but does not meet the seniority threshold defined in the JD. His experience is primarily with monolithic architectures (PHP, MySQL), and there is limited evidence of exposure to distributed systems, containers, or cloud-native patterns. Soft skill indicators from the resume are also below the benchmark for the team culture described. Not recommended for further evaluation at this time.',
    keyStrengths: ['Backend fundamentals', 'Database design skills'],
    keyWeaknesses: ['Monolithic architecture focus', 'No cloud/container experience', 'Below seniority threshold', 'Limited modern stack exposure'],
    scores: [
      { criterionId: 'experience', label: 'Experience', score: 60, weight: 40, weightedScore: 24.0 },
      { criterionId: 'domain-experience', label: 'Domain Experience', score: 65, weight: 25, weightedScore: 16.25 },
      { criterionId: 'projects', label: 'Projects', score: 68, weight: 15, weightedScore: 10.2 },
      { criterionId: 'education', label: 'Education', score: 70, weight: 10, weightedScore: 7.0 },
      { criterionId: 'certifications', label: 'Certifications', score: 50, weight: 5, weightedScore: 2.5 },
      { criterionId: 'technical-skills', label: 'Technical Skills', score: 62, weight: 5, weightedScore: 3.1 },
    ],
  },
]
