import { useState } from 'react'
import { ArrowLeft } from 'lucide-react'
import { useNavigate } from 'react-router-dom'
import { api, ApiError } from '@/api'
import { usePipeline } from '@/store/pipelineStore'

export default function CreateProject() {
  const [form, setForm] = useState({ title: '', target_role: '', department: '', description: '' })
  const [saving, setSaving] = useState(false); const [error, setError] = useState<string | null>(null)
  const navigate = useNavigate(); const { dispatch } = usePipeline()
  const submit = async (e: React.FormEvent) => { e.preventDefault(); setSaving(true); setError(null); try { const project = await api.createProject({ title: form.title.trim(), target_role: form.target_role.trim(), department: form.department.trim() || null, description: form.description.trim() || null, status: 'DRAFT' }); dispatch({ type: 'SELECT_PROJECT', payload: project }); navigate(`/projects/${project.id}/overview`) } catch (err) { setError(err instanceof ApiError ? err.message : 'Unable to create project.') } finally { setSaving(false) } }
  return <div className="max-w-2xl mx-auto py-6"><button onClick={() => navigate('/projects')} className="text-[12px] text-slate-500 flex gap-1 items-center mb-7 hover:text-slate-900"><ArrowLeft size={13}/> Projects</button><div className="card p-8 md:p-10"><h1 className="text-[28px] font-bold tracking-tight text-slate-900">Create a screening project</h1><p className="text-[14px] text-slate-500 mt-2 mb-8">Set up a workspace for this hiring campaign.</p><form onSubmit={submit} className="space-y-5">{[['Project name','title'],['Target role','target_role'],['Department','department']].map(([label,key]) => <label className="block" key={key}><span className="text-[12px] font-semibold text-slate-700">{label}{key!=='department'&&' *'}</span><input required={key==='title'||key==='target_role'} minLength={key==='title'?3:key==='target_role'?2:undefined} value={form[key as keyof typeof form]} onChange={e=>setForm({...form,[key]:e.target.value})} className="mt-2 w-full border border-slate-200 px-3.5 py-3 text-[13px] outline-none"/></label>)}<label className="block"><span className="text-[12px] font-semibold text-slate-700">Description</span><textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})} rows={4} className="mt-2 w-full border border-slate-200 px-3.5 py-3 text-[13px] outline-none resize-none"/></label>{error&&<p className="text-[12px] text-red-600 bg-red-50 rounded-lg p-3">{error}</p>}<div className="pt-2 flex justify-end"><button disabled={saving} className="btn-primary">{saving?'Creating…':'Create Project'}</button></div></form></div></div>
}
