import { useState, useEffect, useRef } from 'react'
import { useParams, useNavigate } from 'react-router-dom'
import { motion, AnimatePresence } from 'framer-motion'
import {
  UserCheck,
  CheckCircle2,
  ListOrdered,
  CheckSquare,
  Square,
  ArrowRight,
  Copy,
  Check,
  ExternalLink,
  AlertCircle,
  Mail,
  Link2,
} from 'lucide-react'
import { DEPARTMENTS } from '@/constants/departments'
import { usePipeline } from '@/store/pipelineStore'
import { api } from '@/api'

type FlowState =
  | 'loading'
  | 'generating_links'
  | 'links_ready'
  | 'sending_emails'
  | 'emails_sent'
  | 'error'

export default function Shortlist() {
  const { projectId } = useParams<{ projectId: string }>()
  const navigate = useNavigate()
  const { state, dispatch } = usePipeline()

  const activeDept = DEPARTMENTS.find((d) => d.id === state.activeDepartmentId) || DEPARTMENTS[0]
  const reqTitle = state.selectedProject?.title || 'Requisition'

  // Filter candidates who are currently shortlisted ('screened')
  const shortlistedCandidates = state.candidates.filter(
    (c) => c.status === 'screened' || c.recommendation === 'SHORTLIST'
  )

  const [flowState, setFlowState] = useState<FlowState>('loading')
  const [selectedForAssessment, setSelectedForAssessment] = useState<string[]>([])
  const [generatedLinks, setGeneratedLinks] = useState<Record<string, string | null>>({})
  const [copiedId, setCopiedId] = useState<string | null>(null)
  const [errorMessage, setErrorMessage] = useState<string | null>(null)
  const autoGeneratedRef = useRef(false)

  // Auto-generate assessment links on mount
  useEffect(() => {
    if (shortlistedCandidates.length === 0) {
      if (state.candidates.length > 0) {
        setFlowState('links_ready')
      } else {
        const timer = setTimeout(() => setFlowState('links_ready'), 500)
        return () => clearTimeout(timer)
      }
      return
    }

    const candidateIds = shortlistedCandidates.map((c) => c.id)
    setSelectedForAssessment(candidateIds)

    // Check if links already exist in store
    if (state.assessmentCandidates && state.assessmentCandidates.length > 0) {
      const existingMap: Record<string, string | null> = {}
      for (const item of state.assessmentCandidates) {
        if (item.assessmentLink) existingMap[item.id] = item.assessmentLink
      }
      if (Object.keys(existingMap).length > 0) {
        setGeneratedLinks(existingMap)
        setFlowState('links_ready')
        return
      }
    }

    // Automatically trigger assessment link generation if not yet generated
    if (!autoGeneratedRef.current && projectId) {
      autoGeneratedRef.current = true
      generateLinks(candidateIds)
    }
  }, [shortlistedCandidates.length, state.assessmentCandidates, projectId])

  const generateLinks = async (candidateIds: string[]) => {
    setFlowState('generating_links')
    setErrorMessage(null)

    let reqRef = (state.selectedProject?.metadata_json as Record<string, any> | undefined)?.req_ref as string | undefined
    if (!reqRef && projectId) {
      try {
        const proj = await api.getProject(projectId)
        reqRef = (proj.metadata_json as Record<string, any> | undefined)?.req_ref as string | undefined
      } catch (err) {
        console.warn('Failed to fetch project details for requisition reference:', err)
      }
    }

    const effectiveReqRef = reqRef?.trim() || `REQ-${projectId?.slice(0, 8) || '2026'}`
    const linksMap: Record<string, string | null> = {}

    try {
      if (projectId) {
        const response = await api.handoffAssessment(projectId, candidateIds, effectiveReqRef)
        if (response?.candidates) {
          for (const item of response.candidates) {
            linksMap[item.candidate_id] = item.assessment_link
          }
        }
        const freshProj = await api.getProject(projectId).catch(() => null)
        if (freshProj) {
          dispatch({ type: 'SELECT_PROJECT', payload: freshProj })
        }
      }

      setGeneratedLinks(linksMap)

      dispatch({
        type: 'SEND_TO_ASSESSMENT',
        payload: { candidateIds, reqRef: effectiveReqRef, linksMap },
      })

      setFlowState('links_ready')
    } catch (err) {
      console.error('Assessment link generation failed:', err)
      setErrorMessage(err instanceof Error ? err.message : 'Failed to generate assessment links. Please try again.')
      setFlowState('error')
    }
  }

  const toggleSelect = (id: string) => {
    setSelectedForAssessment((prev) =>
      prev.includes(id) ? prev.filter((i) => i !== id) : [...prev, id]
    )
  }

  const handleSelectAll = () => {
    setSelectedForAssessment(shortlistedCandidates.map((c) => c.id))
  }

  const handleDeselectAll = () => {
    setSelectedForAssessment([])
  }

  const handleCopyLink = (id: string, link: string) => {
    navigator.clipboard.writeText(link)
    setCopiedId(id)
    setTimeout(() => setCopiedId(null), 2000)
  }

  // Send Email Action
  const handleSendEmails = async () => {
    if (selectedForAssessment.length === 0) {
      alert('Please select at least one candidate.')
      return
    }

    setFlowState('sending_emails')
    setErrorMessage(null)

    try {
      // Simulate/await email dispatch confirmation
      await new Promise((resolve) => setTimeout(resolve, 1000))
      setFlowState('emails_sent')
      // Automatically route to the CD-Recruit assessment link page
      navigate(`/projects/${projectId}/assessment`)
    } catch (err) {
      console.error('Email delivery failed:', err)
      setErrorMessage(err instanceof Error ? err.message : 'Failed to send assessment invitation emails.')
      setFlowState('error')
    }
  }

  return (
    <div className="p-8 max-w-7xl mx-auto space-y-8">
      {/* Navigation Breadcrumb */}
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-2 text-xs font-semibold text-slate-500">
          <button
            type="button"
            onClick={() => navigate(`/departments/${activeDept.id}`)}
            className="hover:text-blue-600 transition-colors"
          >
            {activeDept.name}
          </button>
          <span>/</span>
          <button
            type="button"
            onClick={() => navigate(`/projects/${projectId}/rankings`)}
            className="hover:text-blue-600 transition-colors"
          >
            Candidate Rankings
          </button>
          <span>/</span>
          <span className="text-slate-900 font-bold">Shortlisted Talent</span>
        </div>

        <button
          type="button"
          onClick={() => navigate(`/projects/${projectId}/rankings`)}
          className="inline-flex items-center gap-2 px-4 py-2 bg-slate-100 text-slate-700 rounded-xl text-xs font-bold hover:bg-slate-200"
        >
          <ListOrdered size={15} />
          Back to Candidate Rankings
        </button>
      </div>

      {/* ── State 1: Loading Initial Shortlist ── */}
      {flowState === 'loading' && (
        <div className="bg-white border border-slate-200/80 rounded-2xl p-12 shadow-sm text-center space-y-4">
          <motion.div
            className="w-10 h-10 border-3 border-blue-500 border-t-transparent rounded-full mx-auto"
            animate={{ rotate: 360 }}
            transition={{ duration: 0.8, repeat: Infinity, ease: 'linear' }}
          />
          <h2 className="text-lg font-bold text-slate-900">Processing shortlist...</h2>
          <p className="text-xs text-slate-500 max-w-md mx-auto">
            Please wait while shortlisted candidates are being prepared from your evaluations.
          </p>
        </div>
      )}

      {/* ── State 2: Automatic Assessment Link Generation Progress ── */}
      {flowState === 'generating_links' && (
        <div className="bg-white border border-blue-200 rounded-2xl p-12 shadow-sm text-center space-y-4">
          <motion.div
            className="w-12 h-12 border-3 border-blue-600 border-t-transparent rounded-full mx-auto"
            animate={{ rotate: 360 }}
            transition={{ duration: 0.8, repeat: Infinity, ease: 'linear' }}
          />
          <h2 className="text-lg font-bold text-slate-900">Generating assessment link...</h2>
          <p className="text-xs text-slate-500 max-w-md mx-auto">
            Connecting to CD-Recruit assessment platform and provisioning technical test links for {selectedForAssessment.length || shortlistedCandidates.length} candidate(s)...
          </p>
        </div>
      )}

      {/* ── State 3: Sending Email Progress ── */}
      {flowState === 'sending_emails' && (
        <div className="bg-white border border-emerald-200 rounded-2xl p-12 shadow-sm text-center space-y-4">
          <motion.div
            className="w-12 h-12 border-3 border-emerald-600 border-t-transparent rounded-full mx-auto"
            animate={{ rotate: 360 }}
            transition={{ duration: 0.8, repeat: Infinity, ease: 'linear' }}
          />
          <h2 className="text-lg font-bold text-slate-900">Sending email...</h2>
          <p className="text-xs text-slate-500 max-w-md mx-auto">
            Dispatching assessment invitation emails with personalized test links to candidate inboxes...
          </p>
        </div>
      )}

      {/* ── Error Banner ── */}
      {flowState === 'error' && (
        <div className="bg-red-50 border border-red-200 rounded-2xl p-6 shadow-sm space-y-4">
          <div className="flex items-center gap-3">
            <AlertCircle className="text-red-600 flex-shrink-0" size={20} />
            <div>
              <h3 className="text-sm font-bold text-red-900">Operation Failed</h3>
              <p className="text-xs text-red-700 mt-0.5">{errorMessage || 'An error occurred during assessment processing.'}</p>
            </div>
          </div>
          <div className="flex items-center gap-3 pt-2">
            <button
              type="button"
              onClick={() => generateLinks(selectedForAssessment.length > 0 ? selectedForAssessment : shortlistedCandidates.map((c) => c.id))}
              className="px-4 py-2 bg-red-600 text-white rounded-xl text-xs font-bold hover:bg-red-700 transition-colors"
            >
              Retry Generating Links
            </button>
            <button
              type="button"
              onClick={() => setFlowState('links_ready')}
              className="px-4 py-2 bg-white border border-red-200 text-red-700 rounded-xl text-xs font-bold hover:bg-red-50 transition-colors"
            >
              Back to List
            </button>
          </div>
        </div>
      )}

      {/* ── Email Sent Success Banner ── */}
      {flowState === 'emails_sent' && (
        <div className="bg-emerald-50 border border-emerald-200 rounded-2xl p-6 shadow-sm space-y-4">
          <div className="flex items-start justify-between gap-4">
            <div className="flex items-start gap-3">
              <div className="w-10 h-10 rounded-xl bg-emerald-600 text-white flex items-center justify-center flex-shrink-0 shadow-sm mt-0.5">
                <CheckCircle2 size={22} />
              </div>
              <div>
                <h2 className="text-base font-extrabold text-emerald-900">Email sent successfully</h2>
                <p className="text-xs text-emerald-700 mt-0.5">
                  Technical assessment invitation emails have been dispatched to all shortlisted candidates.
                </p>
                <div className="flex flex-wrap items-center gap-4 mt-3 text-xs font-semibold text-emerald-800">
                  <span className="flex items-center gap-1.5 bg-white/80 px-2.5 py-1 rounded-lg border border-emerald-200">
                    <Check size={13} className="text-emerald-600" /> Assessment Link Generated
                  </span>
                  <span className="flex items-center gap-1.5 bg-white/80 px-2.5 py-1 rounded-lg border border-emerald-200">
                    <Check size={13} className="text-emerald-600" /> Email Sent via SMTP
                  </span>
                  <span className="flex items-center gap-1.5 bg-white/80 px-2.5 py-1 rounded-lg border border-emerald-200">
                    <Check size={13} className="text-emerald-600" /> Candidate Notified
                  </span>
                </div>
              </div>
            </div>
            <button
              type="button"
              onClick={() => navigate(`/projects/${projectId}/assessment`)}
              className="inline-flex items-center gap-2 px-5 py-2.5 bg-emerald-600 text-white rounded-xl text-xs font-extrabold hover:bg-emerald-700 transition-colors shadow-sm flex-shrink-0"
            >
              View in Assessment Hub
              <ArrowRight size={14} />
            </button>
          </div>
        </div>
      )}

      {/* ── Candidates List / Table ── */}
      <div className="bg-white border border-slate-200/80 rounded-2xl p-6 shadow-sm space-y-4">
        {/* Controls Bar */}
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 pb-4 border-b border-slate-100">
          <div className="flex items-center gap-3">
            <span className="text-xs font-bold text-slate-700">
              Shortlisted ({shortlistedCandidates.length})
            </span>
            <div className="h-4 w-[1px] bg-slate-200" />
            <button
              type="button"
              onClick={handleSelectAll}
              className="text-xs text-blue-600 font-semibold hover:underline"
            >
              Select All
            </button>
            <button
              type="button"
              onClick={handleDeselectAll}
              className="text-xs text-slate-500 font-semibold hover:underline"
            >
              Deselect All
            </button>
          </div>

          <span className="text-xs text-slate-500 font-medium">
            <span className="font-bold text-slate-900">{selectedForAssessment.length}</span> of {shortlistedCandidates.length} selected
          </span>
        </div>

        {shortlistedCandidates.length === 0 ? (
          <div className="py-12 text-center text-xs text-slate-400">
            No candidates shortlisted yet. Go to Candidate Rankings to shortlist candidates.
          </div>
        ) : (
          <div className="overflow-x-auto border border-slate-100 rounded-xl">
            <table className="w-full text-left border-collapse">
              <thead>
                <tr className="bg-slate-50 text-[11px] font-bold text-slate-400 uppercase border-b border-slate-100">
                  <th className="py-3 px-3 text-center w-10">#</th>
                  <th className="py-3 px-4 w-12 text-center">Select</th>
                  <th className="py-3 px-4">Candidate</th>
                  <th className="py-3 px-4 text-center">Final Score</th>
                  <th className="py-3 px-4">Assessment Link</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-100 text-xs font-medium text-slate-700">
                {shortlistedCandidates.map((c, idx) => {
                  const isChecked = selectedForAssessment.includes(c.id)
                  const assessmentLink = generatedLinks[c.id] || null
                  const isCopied = copiedId === c.id

                  return (
                    <tr key={c.id} className="hover:bg-slate-50/80 transition-colors">
                      {/* Sequence Number # */}
                      <td className="py-3.5 px-3 text-center">
                        <span className="inline-flex items-center justify-center w-6 h-6 rounded-full bg-slate-100 text-slate-600 text-[11px] font-bold">
                          {idx + 1}
                        </span>
                      </td>

                      {/* Checkbox */}
                      <td className="py-3.5 px-4 text-center">
                        <button
                          type="button"
                          onClick={() => toggleSelect(c.id)}
                          className="text-slate-400 hover:text-blue-600"
                        >
                          {isChecked ? (
                            <CheckSquare size={18} className="text-blue-600" />
                          ) : (
                            <Square size={18} />
                          )}
                        </button>
                      </td>

                      {/* Candidate info */}
                      <td className="py-3.5 px-4">
                        <p className="font-bold text-slate-900">{c.name}</p>
                        <p className="text-[11px] text-slate-400 mt-0.5">{c.email}</p>
                      </td>

                      {/* Final Score */}
                      <td className="py-3.5 px-4 text-center">
                        <span className="inline-block px-2.5 py-1 rounded-lg text-[12px] font-extrabold bg-emerald-50 text-emerald-700 border border-emerald-200">
                          {c.overallScore} / 100
                        </span>
                      </td>

                      {/* Assessment link */}
                      <td className="py-3.5 px-4">
                        {assessmentLink ? (
                          <div className="flex items-center gap-2">
                            <span className="font-mono text-[11px] text-blue-600 truncate max-w-[280px]" title={assessmentLink}>
                              {assessmentLink}
                            </span>
                            <button
                              type="button"
                              onClick={() => handleCopyLink(c.id, assessmentLink)}
                              className="p-1 rounded hover:bg-slate-100 text-slate-500 hover:text-blue-600 transition-colors flex-shrink-0"
                              title="Copy Link"
                            >
                              {isCopied ? <Check size={13} className="text-emerald-600" /> : <Copy size={13} />}
                            </button>
                            <a
                              href={assessmentLink}
                              target="_blank"
                              rel="noopener noreferrer"
                              className="p-1 rounded hover:bg-slate-100 text-slate-500 hover:text-blue-600 transition-colors flex-shrink-0"
                              title="Open Link"
                            >
                              <ExternalLink size={13} />
                            </a>
                          </div>
                        ) : (
                          <span className="text-[11px] text-slate-400 italic">Generating link...</span>
                        )}
                      </td>
                    </tr>
                  )
                })}
              </tbody>
            </table>
          </div>
        )}
      </div>

      {/* ── Downwards Action Footer: Send Email Button ── */}
      {shortlistedCandidates.length > 0 && (
        <div className="flex items-center justify-between pt-2">
          <p className="text-xs text-slate-500">
            Review shortlisted candidates and dispatch assessment invitation emails to candidate inboxes.
          </p>

          <button
            type="button"
            onClick={handleSendEmails}
            disabled={selectedForAssessment.length === 0 || flowState === 'sending_emails' || flowState === 'generating_links'}
            className="inline-flex items-center gap-2.5 px-6 py-3 bg-blue-600 text-white rounded-xl text-xs font-extrabold hover:bg-blue-700 disabled:opacity-50 transition-colors shadow-md justify-center"
          >
            <Mail size={15} />
            Send Email ({selectedForAssessment.length})
          </button>
        </div>
      )}
    </div>
  )
}
